apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    volumeMounts:
    - name: htmldir
      mountPath: /usr/share/nginx/html
    startupProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
  - name: busybox
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: admin
    image: busybox
    volumeMounts:
    - name: htmldir
      mountPath: /html
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do echo $DUMMY_DATABASE_PASSWORD >> /html/index.html && sleep 5; done;" ]
  volumes:
    - name: htmldir
      emptyDir: {}  
